### ISSUE TITLE
Version 1.3.0 referenced in workflow but it doesn't exist

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/ac-version-for-fenix-beta#3]
https://github.com/mozilla-mobile/firefox-android/blob/main/.github/workflows/ac-sync-strings.yml#L23

I see commits in the repo, so I assume this was never released. Mistake or by design?

**Comment by JohanLorenzo** [comment]
Hey @flodolo! You don't need an actual Github release to use a Github action. You can reference a git-commit or - which is the case here - a git-tag: https://github.com/mozilla-mobile/ac-version-for-fenix-beta/releases/tag/1.3.0. That's how 1.3.0 is used 🙂 

I don't mind creating a Github release, if that helps 🙂

**Comment by flodolo** [comment]
D'oh, I didn't think of checking for tags, since the release was missing.

I though GitHub was just falling back to the closest existing release, which seems more dangerous than helpful.

For clarity and consistency, it's probably worth creating one?
https://github.com/mozilla-mobile/ac-version-for-fenix-beta/releases

**Comment by JohanLorenzo** [comment]
All right, done! https://github.com/mozilla-mobile/ac-version-for-fenix-beta/releases/tag/1.3.0
